## Q1. Numpy Array Operations


1. Create a 1-D numpy (`arr_1d`) array with numbers (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71)

In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

# your code here
arr_1d=np.array((2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71))
arr_1d

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71])

2. Compute the sum of squared errors of `arr_1d`.
mean

In [7]:
# your code here
for i in arr_1d:
    SSE=+(i-arr_1d.mean())**2
SSE

1524.9024999999997

3. show all elements of `arr_1d` that are at odd-indices.

In [8]:
# your code here
odd_indices=[arr_1d[i] for i in range(0,len(arr_1d)) if i%2==1]
odd_indices

[3, 7, 13, 19, 29, 37, 43, 53, 61, 71]

4. show all elements of `arr_1d` that are larger than 40.

In [9]:
# your code here
larger_than_40=[i for i in arr_1d if i>40]

larger_than_40

[41, 43, 47, 53, 59, 61, 67, 71]

5. show all elements of `arr_1d` at even-indices and smaller than 40.

In [10]:
# your code here
a=[arr_1d[i] for i in range(0, len(arr_1d)) if i%2==0 and arr_1d[i]<40]
a

[2, 5, 11, 17, 23, 31]

6. Create a 2-d array of which the first column contains elements of `arr_1d` at even-indices and the second column contains elements of `arr_1d` at even-indices.

In [11]:
# your code here
even_indices=[arr_1d[i] for i in range(0,len(arr_1d)) if i%2==0]
even_indices
d2 =arr_1d.reshape(10,2)
d2[0:,1] =even_indices

d2


array([[ 2,  2],
       [ 5,  5],
       [11, 11],
       [17, 17],
       [23, 23],
       [31, 31],
       [41, 41],
       [47, 47],
       [59, 59],
       [67, 67]])

7. Using `arr_1d` create a 2-d array of shape (5,4), `arr_2d`.

In [12]:
# your code here
arr_1d=np.array((2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71))
arr_2d=arr_1d.reshape(5,4)
arr_2d

array([[ 2,  3,  5,  7],
       [11, 13, 17, 19],
       [23, 29, 31, 37],
       [41, 43, 47, 53],
       [59, 61, 67, 71]])

8. Add the array of the first 4 elements of `arr_1d` to each row of `arr_2d`.

In [13]:
# your code here
arr_1d=np.array((2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71))
arr_2d=arr_1d.reshape(5,4)
a=arr_1d[0:4]
arr_2d+a

array([[ 4,  6, 10, 14],
       [13, 16, 22, 26],
       [25, 32, 36, 44],
       [43, 46, 52, 60],
       [61, 64, 72, 78]])

9. Add the array of the last 5 elements of `arr_1d` to each column of `arr_2d`.

In [14]:
# your code here
arr_1d=np.array((2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71))
arr_2d=arr_1d.reshape(5,4)
b=arr_1d[-5:]
(arr_2d.T+b).T

array([[ 55,  56,  58,  60],
       [ 70,  72,  76,  78],
       [ 84,  90,  92,  98],
       [108, 110, 114, 120],
       [130, 132, 138, 142]])

10. Create the new 2-D array of shape (5,5), denoted `arr_2d_new,` by appending the array of the 5 elements starting from the element at the 7_th index to `arr_1d`

In [ ]:
# your code here
arr_1d=np.array((2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71))
arr_2d=arr_1d.reshape(5,4)
arr_2d_new=np.vstack((arr_2d.T,[arr_1d[7:12]])).T
arr_2d_new

array([[ 2,  3,  5,  7, 19],
       [11, 13, 17, 19, 23],
       [23, 29, 31, 37, 29],
       [41, 43, 47, 53, 31],
       [59, 61, 67, 71, 37]])

10. Compute the row-wise sum of `arr_2d_new`

In [16]:
# your code here
arr_2d_new.sum(axis=0)

array([136, 149, 167, 187, 139])

11. Compute the column-wise sum of `arr_2d_new`

In [17]:
# your code here
arr_2d_new.sum(axis=1)

array([ 36,  83, 149, 215, 295])

## Q2. Approximation of the Sine Functions

It is well known that the sine function can be approximated by the infinite order of the Maclaurin series: $$\sin{x} = x - \dfrac{x^3}{3!} + \dfrac{x^5}{5!} - \dfrac{x^7}{7!} \cdots = \sum_{n=0}^{\infty } \dfrac {(-1)^n}{(2n+1)!} x^{2n+1}$$


1. Write a **lambda function** to approximate $\sin{x}$ with the $N^{th}$ order Maclaurin series.


In [18]:
import math

sin_approx = lambda x,N : sum(x**(2*i+1)*(-1)**i/math.factorial(2*i+1) for i in range(N))


2. Set $N=5$ and compute $\sin{x}$ where $x$ is equally spaced array of 50 numbers in the interval $[-2\pi, 2\pi]$.

In [19]:
# your code here

vec1=np.linspace(-2*np.pi, 2*np.pi, 50)

np.sin(vec1).flatten()

array([ 2.44929360e-16,  2.53654584e-01,  4.90717552e-01,  6.95682551e-01,
        8.55142763e-01,  9.58667853e-01,  9.99486216e-01,  9.74927912e-01,
        8.86599306e-01,  7.40277997e-01,  5.45534901e-01,  3.15108218e-01,
        6.40702200e-02, -1.91158629e-01, -4.33883739e-01, -6.48228395e-01,
       -8.20172255e-01, -9.38468422e-01, -9.95379113e-01, -9.87181783e-01,
       -9.14412623e-01, -7.81831482e-01, -5.98110530e-01, -3.75267005e-01,
       -1.27877162e-01,  1.27877162e-01,  3.75267005e-01,  5.98110530e-01,
        7.81831482e-01,  9.14412623e-01,  9.87181783e-01,  9.95379113e-01,
        9.38468422e-01,  8.20172255e-01,  6.48228395e-01,  4.33883739e-01,
        1.91158629e-01, -6.40702200e-02, -3.15108218e-01, -5.45534901e-01,
       -7.40277997e-01, -8.86599306e-01, -9.74927912e-01, -9.99486216e-01,
       -9.58667853e-01, -8.55142763e-01, -6.95682551e-01, -4.90717552e-01,
       -2.53654584e-01, -2.44929360e-16])

3. Compute the approximation errors for the function that you wrote above by comparing the values from your function and those from the sine function in the Numpy library.

In [20]:


vec1=np.linspace(-2*np.pi, 2*np.pi, 50)

sin_approx(vec1,5).flatten()

array([-11.89956653,  -7.40645458,  -4.3402248 ,  -2.28369224,
        -0.93796264,  -0.09191445,   0.4019134 ,   0.64601469,
         0.71207816,   0.65141337,   0.50234616,   0.2952053 ,
         0.05544337,  -0.19464027,  -0.43517531,  -0.64866149,
        -0.82030063,  -0.93850104,  -0.99538591,  -0.98718287,
        -0.91441274,  -0.78183149,  -0.59811053,  -0.375267  ,
        -0.12787716,   0.12787716,   0.375267  ,   0.59811053,
         0.78183149,   0.91441274,   0.98718287,   0.99538591,
         0.93850104,   0.82030063,   0.64866149,   0.43517531,
         0.19464027,  -0.05544337,  -0.2952053 ,  -0.50234616,
        -0.65141337,  -0.71207816,  -0.64601469,  -0.4019134 ,
         0.09191445,   0.93796264,   2.28369224,   4.3402248 ,
         7.40645458,  11.89956653])

In [21]:
approx_errors=sin_approx(vec1,5) - np.sin(vec1)
approx_errors


array([-1.18995665e+01, -7.66010916e+00, -4.83094235e+00, -2.97937479e+00,
       -1.79310540e+00, -1.05058230e+00, -5.97572818e-01, -3.28913222e-01,
       -1.74521149e-01, -8.88646231e-02, -4.31887459e-02, -1.99029149e-02,
       -8.62685053e-03, -3.48163967e-03, -1.29157192e-03, -4.33094950e-04,
       -1.28372737e-04, -3.26159230e-05, -6.79736040e-06, -1.08758665e-06,
       -1.20125021e-07, -7.59458829e-09, -1.88015048e-10, -6.83231249e-13,
        0.00000000e+00,  2.77555756e-17,  6.83231249e-13,  1.88015048e-10,
        7.59458829e-09,  1.20125020e-07,  1.08758665e-06,  6.79736040e-06,
        3.26159230e-05,  1.28372737e-04,  4.33094950e-04,  1.29157192e-03,
        3.48163967e-03,  8.62685053e-03,  1.99029149e-02,  4.31887459e-02,
        8.88646231e-02,  1.74521149e-01,  3.28913222e-01,  5.97572818e-01,
        1.05058230e+00,  1.79310540e+00,  2.97937479e+00,  4.83094235e+00,
        7.66010916e+00,  1.18995665e+01])

4. Write the Python code to find $N$ that makes the maximum approximation error of your function for $x\in [-2\pi, 2\pi]$ less than 1.0e-10.

In [22]:

#N은 클수록 에러가 작아진다.

In [23]:

N=1
vec1=np.linspace(-2*np.pi, 2*np.pi, 100)
while True:
    if (sin_approx(vec1,N) - np.sin(vec1)).max() <1.0e-10:
        print(N)
        break
    else:
        N+=1


        




16


## Q3. Geometric and Harmonic Means

1. Look up the definitioin of `geometric` and `harmonic` means and write two lambda functions to compute those using their definitions.

In [127]:
# your code here
import math 

GM = lambda vec :math.exp((1/len(vec))*sum([math.log(i) for i in vec]))

#GM = lambda vec : (vec.prod())**(1/len(vec)) << Runningtimewarning이 뜨면서 0의 값만 나온다.


HM = lambda vec : len(vec)/sum((1/i) for i in vec)



2. Generate a 1-d Numpy array $X$ of 100 random integers.

In [128]:
# your code here
X=np.random.randint(1,500,size=100)
X


array([192, 459, 401, 147, 260,  72, 154, 179,  17, 291, 467, 426, 264,
       440,  27, 462, 223, 220, 150, 494, 204, 446, 377,  91, 257,   3,
       260, 218, 433,  54, 290,  18, 386,  43,  81, 276,  23, 478, 389,
       277, 325, 343, 423,   2, 166,  98, 264, 302,  57, 326, 456, 177,
        35, 113, 389, 427,  48, 470,  17,  18, 156, 407, 477, 450, 425,
       435, 115, 462, 121,  51, 483, 118,  91, 282, 246, 467, 375, 369,
       213, 159, 159, 320, 189, 359,  77, 211, 424,  30,   5, 411, 287,
       145, 376, 210,  25,  12, 165, 156, 237,  75])

3. Using the functions that you wrote above, compute the geometric and harmonic means of the array $X$.

In [129]:

GM(X) 


160.55010761028362

In [130]:
HM(X)

49.88521124362038

4. There are already functions to compute the geometric and harmonic means in the `statistics` library. Use these functions, compute the geometric and harmonic means again and compare the results with those from your functions.

In [131]:
import statistics as st

st.geometric_mean(X)

160.55010761028376

In [132]:
st.harmonic_mean(X)

49.88521124362037

## Q4. Simulation for Linear Regression

Suppose that the true relationship between the dependent variable ($y$) and three explanatory variables ($X_1$, $X_2$ and $X_3$) are given as follows: $$ y_t = 2 + 4 X_{1,t}  + 6 X_{2,t}  + 8 X_{3,t} + \epsilon_t,$$ where $\epsilon \sim N(0, 0.04)$ and  $t = 1, 2, \cdots, T$. This relationship can be written in matrix form: $\mathbf{y} = \mathbf{X}\beta$, where $\mathbf{y} = (y_1, y_2, \cdots, y_T)'$, $\mathbf{X} = (\mathbf{1}, \mathbf{X}_{1}, \mathbf{X}_{2}, \mathbf{X}_{3})$ and $\beta = (2,4,6,8)'$.

The economist does not know the true relationship but only has dataset of ($X, y$) and wants to figure out the relationship between $X$ and $y$ based on linear models. The Ordinary Least Squares (OLS) estimates of the coefficients is $$\hat{\beta} = (\mathbf{X'}\mathbf{X})^{-1}\mathbf{X'}\mathbf{y}$$


1. Create the matrix ($\mathbf{X}$) of explanatory variables assuing that:
  - the first column contains 100 ones.
  - the second column contains 100 numbers from $N(2, 5)$
  - the third column contains 100 numbers from $N(3, 3)$
  - the fourth column contains 100 numbers from $N(5, 2)$

  Check whether explanatory variables are created as specified.

In [133]:
r_1= np.full((1,100),1)
r_2= np.random.normal(2,5, (1,100))
r_3= np.random.normal(3,3, (1,100))
r_4= np.random.normal(5,2, (1,100))
X=np.vstack((r_1,r_2,r_3,r_4)).T

X



array([[  1.        ,   1.00979663,   1.79417588,   7.22203282],
       [  1.        ,  12.41890173,  -0.04320025,   2.97224377],
       [  1.        ,   2.98330987,   1.81355788,   2.78503747],
       [  1.        ,  -0.13153828,   4.96139337,   3.22493647],
       [  1.        ,   1.26602338,   4.43428505,   6.17173327],
       [  1.        ,   2.47042841,   0.1111917 ,   8.44053561],
       [  1.        ,   4.62349297,   3.17336722,   4.19916368],
       [  1.        ,  -5.66555057,   2.18728488,   4.5867287 ],
       [  1.        ,   3.64297746,   7.36836256,   2.31016261],
       [  1.        ,  -4.08360631,   0.38510314,   5.58702544],
       [  1.        ,   4.95850966,   0.64538032,   2.56471811],
       [  1.        ,   5.21447076,   8.49952704,  10.13050613],
       [  1.        ,   2.5015755 ,   5.03367602,   5.39715154],
       [  1.        ,   1.03135504,   2.03101736,   5.80759131],
       [  1.        ,   0.540415  ,   1.94709218,   6.55659899],
       [  1.        ,   6

  2. Create the vector of dependent variable ($\mathbf{y}$) using the true relationship above.

In [116]:
b=np.array([2,4,6,8]).reshape(4,1)
y=X@b
y


array([[118.33629236],
       [ 92.95363755],
       [ 49.64102273],
       [ 52.26155456],
       [ 65.00289222],
       [ 77.81731011],
       [ 53.67932345],
       [137.38114511],
       [101.7955625 ],
       [ 65.13940032],
       [ 89.24544303],
       [ 74.51430713],
       [ 92.43591894],
       [ 71.45872651],
       [ 79.73889218],
       [ 54.45495896],
       [ 78.41789466],
       [ 48.42562516],
       [ 96.83601992],
       [ 33.89835119],
       [ 91.21488031],
       [ 62.28411554],
       [ 98.48207215],
       [ 84.2731066 ],
       [ 96.29470901],
       [ 21.10181867],
       [ 30.07432989],
       [ 90.89232825],
       [ 60.21987118],
       [ 55.83521168],
       [ 38.1187758 ],
       [ 86.78889268],
       [ 38.96746076],
       [103.63517133],
       [ 78.63268812],
       [ 84.92861484],
       [ 90.04963732],
       [ 71.77926711],
       [ 82.27625986],
       [ 71.4304675 ],
       [120.67907058],
       [ 95.76018426],
       [-17.95837399],
       [ 95

3. Compute the estimates of coefficients.

In [117]:
np.linalg.inv(X.T@X) @ X.T @y


array([[2.],
       [4.],
       [6.],
       [8.]])

4. From the OLS equation, the estimates of the coefficients, $\hat{\beta}$, can be interprested as the solution to a linear equation system. Write the linear equation system and `solve` for it.   

$$\mathbf{X'}\mathbf{y} = (\mathbf{X'}\mathbf{X})\hat{\beta}$$

In [118]:
#(X.T@X)@b_est = X.T@y << THE linear system 
b_est=np.linalg.solve(X.T@X, X.T@y)
b_est

array([[2.],
       [4.],
       [6.],
       [8.]])

5. Suppose that the economist thinks that the explanaroty variable $X_3$ is not important for the dependent variable. Hence she drop that variable from her estimation equation. Compute the estimates $\tilde{\beta}$ with this specification and explain how $\tilde{\beta}$ compare with $\hat{\beta}$.

In [135]:
r_1= np.full((1,100),1)
r_2= np.random.normal(2,5, (1,100))
r_3= np.random.normal(3,3, (1,100))

X_2=np.vstack((r_1,r_2,r_3)).T

b_2=np.array([2,4,6]).reshape(3,1)
y_2=X_2@b_2

b_est_2=np.linalg.solve(X_2.T@X_2, X_2.T@y_2)
b_est_2

#X_3의 계수에 해당하는 원소가 빠진 것을 제외하고는 동일하다.



array([[2.],
       [4.],
       [6.]])

6. The economist is not interested in the constant term. Hence she converted her estimation model to the form of deviations from means:  $$y - \bar{y} = \left(\mathbf{X}-\mathbf{\bar{X}} \right) \gamma,$$ where $\bar{\mathbf{y}}$ and $\bar{\mathbf{X}}$ are the means of $\mathbf{y}$ and $\mathbf{X}$ respectively. Write down the OLS estimates for $\gamma$, compute $\hat{\gamma}$ and compare $\hat{\gamma}$ and $\hat{\beta}$.

In [120]:
y_mean=y.mean()
X_mean=X.mean(axis=0)
A=X-X_mean
b=y-y_mean
#상수항에 관심이 없으므로 & 역행렬 계산을 위하여, 상수항을 버린다.
A=np.delete (A, 0, axis=1)
r_est = np.linalg.solve(A.T@A , A.T@b)
r_est


array([[4.],
       [6.],
       [8.]])

In [121]:
print(r_est)
print(b_est)
# 상수항이 제외된 것 외엔 동일한 결과값이 나온다.

[[4.]
 [6.]
 [8.]]
[[2.]
 [4.]
 [6.]
 [8.]]
